/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSubmitRouteImport } from './routes/_app/submit'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppNotificationsRouteImport } from './routes/_app/notifications'
import { Route as AppInsightsRouteImport } from './routes/_app/insights'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppComplaintsRouteImport } from './routes/_app/complaints'
import { Route as AppAdminRouteImport } from './routes/_app/admin'
import { Route as AppDepartmentIndexRouteImport } from './routes/_app/department/index'
import { Route as AppAdminIndexRouteImport } from './routes/_app/admin.index'
import { Route as AppDepartmentResponsesRouteImport } from './routes/_app/department/responses'
import { Route as AppDepartmentNotificationsRouteImport } from './routes/_app/department/notifications'
import { Route as AppDepartmentComplaintsRouteImport } from './routes/_app/department/complaints'
import { Route as AppComplaintsIdRouteImport } from './routes/_app/complaints.$id'
import { Route as AppAdminDepartmentsRouteImport } from './routes/_app/admin.departments'
import { Route as AppAdminComplaintsRouteImport } from './routes/_app/admin.complaints'
import { Route as AppAdminAnalyticsRouteImport } from './routes/_app/admin.analytics'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSubmitRoute = AppSubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppInsightsRoute = AppInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppComplaintsRoute = AppComplaintsRouteImport.update({
  id: '/complaints',
  path: '/complaints',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppDepartmentIndexRoute = AppDepartmentIndexRouteImport.update({
  id: '/department/',
  path: '/department/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppDepartmentResponsesRoute = AppDepartmentResponsesRouteImport.update({
  id: '/department/responses',
  path: '/department/responses',
  getParentRoute: () => AppRoute,
} as any)
const AppDepartmentNotificationsRoute =
  AppDepartmentNotificationsRouteImport.update({
    id: '/department/notifications',
    path: '/department/notifications',
    getParentRoute: () => AppRoute,
  } as any)
const AppDepartmentComplaintsRoute = AppDepartmentComplaintsRouteImport.update({
  id: '/department/complaints',
  path: '/department/complaints',
  getParentRoute: () => AppRoute,
} as any)
const AppComplaintsIdRoute = AppComplaintsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppComplaintsRoute,
} as any)
const AppAdminDepartmentsRoute = AppAdminDepartmentsRouteImport.update({
  id: '/departments',
  path: '/departments',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminComplaintsRoute = AppAdminComplaintsRouteImport.update({
  id: '/complaints',
  path: '/complaints',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminAnalyticsRoute = AppAdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AppAdminRouteWithChildren
  '/complaints': typeof AppComplaintsRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/insights': typeof AppInsightsRoute
  '/notifications': typeof AppNotificationsRoute
  '/profile': typeof AppProfileRoute
  '/settings': typeof AppSettingsRoute
  '/submit': typeof AppSubmitRoute
  '/admin/analytics': typeof AppAdminAnalyticsRoute
  '/admin/complaints': typeof AppAdminComplaintsRoute
  '/admin/departments': typeof AppAdminDepartmentsRoute
  '/complaints/$id': typeof AppComplaintsIdRoute
  '/department/complaints': typeof AppDepartmentComplaintsRoute
  '/department/notifications': typeof AppDepartmentNotificationsRoute
  '/department/responses': typeof AppDepartmentResponsesRoute
  '/admin/': typeof AppAdminIndexRoute
  '/department/': typeof AppDepartmentIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/complaints': typeof AppComplaintsRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/insights': typeof AppInsightsRoute
  '/notifications': typeof AppNotificationsRoute
  '/profile': typeof AppProfileRoute
  '/settings': typeof AppSettingsRoute
  '/submit': typeof AppSubmitRoute
  '/admin/analytics': typeof AppAdminAnalyticsRoute
  '/admin/complaints': typeof AppAdminComplaintsRoute
  '/admin/departments': typeof AppAdminDepartmentsRoute
  '/complaints/$id': typeof AppComplaintsIdRoute
  '/department/complaints': typeof AppDepartmentComplaintsRoute
  '/department/notifications': typeof AppDepartmentNotificationsRoute
  '/department/responses': typeof AppDepartmentResponsesRoute
  '/admin': typeof AppAdminIndexRoute
  '/department': typeof AppDepartmentIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/_app/admin': typeof AppAdminRouteWithChildren
  '/_app/complaints': typeof AppComplaintsRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/insights': typeof AppInsightsRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/submit': typeof AppSubmitRoute
  '/_app/admin/analytics': typeof AppAdminAnalyticsRoute
  '/_app/admin/complaints': typeof AppAdminComplaintsRoute
  '/_app/admin/departments': typeof AppAdminDepartmentsRoute
  '/_app/complaints/$id': typeof AppComplaintsIdRoute
  '/_app/department/complaints': typeof AppDepartmentComplaintsRoute
  '/_app/department/notifications': typeof AppDepartmentNotificationsRoute
  '/_app/department/responses': typeof AppDepartmentResponsesRoute
  '/_app/admin/': typeof AppAdminIndexRoute
  '/_app/department/': typeof AppDepartmentIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/complaints'
    | '/dashboard'
    | '/insights'
    | '/notifications'
    | '/profile'
    | '/settings'
    | '/submit'
    | '/admin/analytics'
    | '/admin/complaints'
    | '/admin/departments'
    | '/complaints/$id'
    | '/department/complaints'
    | '/department/notifications'
    | '/department/responses'
    | '/admin/'
    | '/department/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/complaints'
    | '/dashboard'
    | '/insights'
    | '/notifications'
    | '/profile'
    | '/settings'
    | '/submit'
    | '/admin/analytics'
    | '/admin/complaints'
    | '/admin/departments'
    | '/complaints/$id'
    | '/department/complaints'
    | '/department/notifications'
    | '/department/responses'
    | '/admin'
    | '/department'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/_app/admin'
    | '/_app/complaints'
    | '/_app/dashboard'
    | '/_app/insights'
    | '/_app/notifications'
    | '/_app/profile'
    | '/_app/settings'
    | '/_app/submit'
    | '/_app/admin/analytics'
    | '/_app/admin/complaints'
    | '/_app/admin/departments'
    | '/_app/complaints/$id'
    | '/_app/department/complaints'
    | '/_app/department/notifications'
    | '/_app/department/responses'
    | '/_app/admin/'
    | '/_app/department/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/submit': {
      id: '/_app/submit'
      path: '/submit'
      fullPath: '/submit'
      preLoaderRoute: typeof AppSubmitRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/insights': {
      id: '/_app/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof AppInsightsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/complaints': {
      id: '/_app/complaints'
      path: '/complaints'
      fullPath: '/complaints'
      preLoaderRoute: typeof AppComplaintsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/department/': {
      id: '/_app/department/'
      path: '/department'
      fullPath: '/department/'
      preLoaderRoute: typeof AppDepartmentIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/': {
      id: '/_app/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/department/responses': {
      id: '/_app/department/responses'
      path: '/department/responses'
      fullPath: '/department/responses'
      preLoaderRoute: typeof AppDepartmentResponsesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/department/notifications': {
      id: '/_app/department/notifications'
      path: '/department/notifications'
      fullPath: '/department/notifications'
      preLoaderRoute: typeof AppDepartmentNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/department/complaints': {
      id: '/_app/department/complaints'
      path: '/department/complaints'
      fullPath: '/department/complaints'
      preLoaderRoute: typeof AppDepartmentComplaintsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/complaints/$id': {
      id: '/_app/complaints/$id'
      path: '/$id'
      fullPath: '/complaints/$id'
      preLoaderRoute: typeof AppComplaintsIdRouteImport
      parentRoute: typeof AppComplaintsRoute
    }
    '/_app/admin/departments': {
      id: '/_app/admin/departments'
      path: '/departments'
      fullPath: '/admin/departments'
      preLoaderRoute: typeof AppAdminDepartmentsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/complaints': {
      id: '/_app/admin/complaints'
      path: '/complaints'
      fullPath: '/admin/complaints'
      preLoaderRoute: typeof AppAdminComplaintsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/analytics': {
      id: '/_app/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AppAdminAnalyticsRouteImport
      parentRoute: typeof AppAdminRoute
    }
  }
}

interface AppAdminRouteChildren {
  AppAdminAnalyticsRoute: typeof AppAdminAnalyticsRoute
  AppAdminComplaintsRoute: typeof AppAdminComplaintsRoute
  AppAdminDepartmentsRoute: typeof AppAdminDepartmentsRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminAnalyticsRoute: AppAdminAnalyticsRoute,
  AppAdminComplaintsRoute: AppAdminComplaintsRoute,
  AppAdminDepartmentsRoute: AppAdminDepartmentsRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppComplaintsRouteChildren {
  AppComplaintsIdRoute: typeof AppComplaintsIdRoute
}

const AppComplaintsRouteChildren: AppComplaintsRouteChildren = {
  AppComplaintsIdRoute: AppComplaintsIdRoute,
}

const AppComplaintsRouteWithChildren = AppComplaintsRoute._addFileChildren(
  AppComplaintsRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppComplaintsRoute: typeof AppComplaintsRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRoute
  AppInsightsRoute: typeof AppInsightsRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSubmitRoute: typeof AppSubmitRoute
  AppDepartmentComplaintsRoute: typeof AppDepartmentComplaintsRoute
  AppDepartmentNotificationsRoute: typeof AppDepartmentNotificationsRoute
  AppDepartmentResponsesRoute: typeof AppDepartmentResponsesRoute
  AppDepartmentIndexRoute: typeof AppDepartmentIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRouteWithChildren,
  AppComplaintsRoute: AppComplaintsRouteWithChildren,
  AppDashboardRoute: AppDashboardRoute,
  AppInsightsRoute: AppInsightsRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppProfileRoute: AppProfileRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSubmitRoute: AppSubmitRoute,
  AppDepartmentComplaintsRoute: AppDepartmentComplaintsRoute,
  AppDepartmentNotificationsRoute: AppDepartmentNotificationsRoute,
  AppDepartmentResponsesRoute: AppDepartmentResponsesRoute,
  AppDepartmentIndexRoute: AppDepartmentIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
